drivers: initialize voltage table
sm8450/drivers/thermal/qcom/cpu_voltage_cooling.c:199:6: error:
variable 'cpu2_freq_table' is used uninitialized whenever
'if' condition is true [-Werror,-Wsometimes-uninitialized]
  199 |         if (table_ct[0] <= 0)
      |             ^~~~~~~~~~~~~~~~~
sm8450/drivers/thermal/qcom/cpu_voltage_cooling.c:221:8: note:
uninitialized use occurs here
  221 |         kfree(cpu2_freq_table);
      |               ^~~~~~~~~~~~~~~
sm8450/drivers/thermal/qcom/cpu_voltage_cooling.c:199:2: note:
remove the 'if' if its condition is always false
  199 |         if (table_ct[0] <= 0)
      |         ^~~~~~~~~~~~~~~~~~~~~
  200 |                 goto opp_err_exit;
      |                 ~~~~~~~~~~~~~~~~~
sm8450/drivers/thermal/qcom/cpu_voltage_cooling.c:181:61: note:
initialize the variable 'cpu2_freq_table' to silence this warning
  181 |         struct limits_freq_table *cpu1_freq_table, *cpu2_freq_table;
      |                                                                    ^
      |                                                                     = NULL